// AUTOGENERATED — DO NOT EDIT. Run: pnpm -F @remis/design-system build:web
// Source of truth: tokens.json

export const tokens = {
  "color": {
    "brand": {
      "primary": {
        "light": "#1B2A4E",
        "dark": "#7CA0FF"
      },
      "primary_hover": {
        "light": "#243762",
        "dark": "#9CB7FF"
      },
      "accent": {
        "light": "#D97706",
        "dark": "#F59E0B"
      },
      "accent_hover": {
        "light": "#B45309",
        "dark": "#FBBF24"
      }
    },
    "neutral": {
      "0": {
        "light": "#FFFFFF",
        "dark": "#0A0B0F"
      },
      "50": {
        "light": "#FAFAFA",
        "dark": "#101218"
      },
      "100": {
        "light": "#F4F4F5",
        "dark": "#181B23"
      },
      "200": {
        "light": "#E4E4E7",
        "dark": "#23262F"
      },
      "300": {
        "light": "#D4D4D8",
        "dark": "#2E323D"
      },
      "400": {
        "light": "#A1A1AA",
        "dark": "#52576B"
      },
      "500": {
        "light": "#71717A",
        "dark": "#7B8194"
      },
      "600": {
        "light": "#52525B",
        "dark": "#A4AABB"
      },
      "700": {
        "light": "#3F3F46",
        "dark": "#C7CCDB"
      },
      "800": {
        "light": "#27272A",
        "dark": "#E4E7EF"
      },
      "900": {
        "light": "#18181B",
        "dark": "#F4F5F9"
      }
    },
    "semantic": {
      "success": {
        "default": {
          "light": "#16A34A",
          "dark": "#22C55E"
        },
        "bg": {
          "light": "#F0FDF4",
          "dark": "#0E2417"
        }
      },
      "warning": {
        "default": {
          "light": "#CA8A04",
          "dark": "#EAB308"
        },
        "bg": {
          "light": "#FEFCE8",
          "dark": "#1F1B0E"
        }
      },
      "danger": {
        "default": {
          "light": "#DC2626",
          "dark": "#EF4444"
        },
        "bg": {
          "light": "#FEF2F2",
          "dark": "#27110F"
        }
      },
      "info": {
        "default": {
          "light": "#2563EB",
          "dark": "#60A5FA"
        },
        "bg": {
          "light": "#EFF6FF",
          "dark": "#0E1B2D"
        }
      }
    },
    "driver_status": {
      "available": {
        "light": "#16A34A",
        "dark": "#22C55E"
      },
      "en_route_to_pickup": {
        "light": "#2563EB",
        "dark": "#60A5FA"
      },
      "waiting_passenger": {
        "light": "#CA8A04",
        "dark": "#EAB308"
      },
      "on_trip": {
        "light": "#DC2626",
        "dark": "#EF4444"
      },
      "on_break": {
        "light": "#FACC15",
        "dark": "#FDE047"
      },
      "offline": {
        "light": "#71717A",
        "dark": "#7B8194"
      },
      "suspended": {
        "light": "#A855F7",
        "dark": "#C084FC"
      }
    },
    "ride_status": {
      "unassigned_urgent": {
        "border": {
          "light": "#DC2626",
          "dark": "#EF4444"
        },
        "bg": {
          "light": "#F4F4F5",
          "dark": "#181B23"
        }
      },
      "broadcasted": {
        "border": {
          "light": "#2563EB",
          "dark": "#60A5FA"
        },
        "bg": {
          "light": "#F4F4F5",
          "dark": "#181B23"
        }
      },
      "in_assignment_window": {
        "border": {
          "light": "#CA8A04",
          "dark": "#EAB308"
        },
        "bg": {
          "light": "#FEFCE8",
          "dark": "#1F1B0E"
        }
      },
      "scheduled": {
        "border": {
          "light": "#2563EB",
          "dark": "#60A5FA"
        },
        "bg": {
          "light": "#EFF6FF",
          "dark": "#0E1B2D"
        }
      },
      "in_progress": {
        "border": {
          "light": "#16A34A",
          "dark": "#22C55E"
        },
        "bg": {
          "light": "#F0FDF4",
          "dark": "#0E2417"
        }
      },
      "hold": {
        "border": {
          "light": "#A1A1AA",
          "dark": "#52576B"
        },
        "bg": {
          "light": "#F4F4F5",
          "dark": "#181B23"
        }
      }
    }
  },
  "font": {
    "family": {
      "display": "Inter Tight",
      "body": "Inter",
      "mono": "Geist Mono"
    },
    "size": {
      "2xs": "10px",
      "xs": "12px",
      "sm": "14px",
      "base": "16px",
      "md": "18px",
      "lg": "20px",
      "xl": "24px",
      "2xl": "30px",
      "3xl": "36px",
      "4xl": "48px",
      "5xl": "60px"
    },
    "weight": {
      "regular": "400",
      "medium": "500",
      "semibold": "600",
      "bold": "700"
    },
    "line_height": {
      "tight": "1.05",
      "snug": "1.2",
      "normal": "1.5",
      "relaxed": "1.6"
    },
    "letter_spacing": {
      "tight": "-0.02em",
      "normal": "0em",
      "wide": "0.06em",
      "wider": "0.1em"
    }
  },
  "space": {
    "0": "0px",
    "2": "2px",
    "4": "4px",
    "6": "6px",
    "8": "8px",
    "12": "12px",
    "16": "16px",
    "20": "20px",
    "24": "24px",
    "32": "32px",
    "40": "40px",
    "48": "48px",
    "64": "64px",
    "80": "80px",
    "96": "96px",
    "128": "128px"
  },
  "radius": {
    "sm": "4px",
    "md": "8px",
    "lg": "12px",
    "xl": "16px",
    "2xl": "24px",
    "full": "9999px"
  },
  "shadow": {
    "xs": {
      "light": "0 1px 2px rgba(15,23,42,0.05)",
      "dark": "inset 0 0 0 1px rgba(255,255,255,0.05)"
    },
    "sm": {
      "light": "0 1px 3px rgba(15,23,42,0.06),0 1px 2px rgba(15,23,42,0.04)",
      "dark": "inset 0 0 0 1px rgba(255,255,255,0.05)"
    },
    "md": {
      "light": "0 4px 6px -1px rgba(15,23,42,0.07),0 2px 4px -2px rgba(15,23,42,0.05)",
      "dark": "inset 0 0 0 1px rgba(255,255,255,0.05)"
    },
    "lg": {
      "light": "0 10px 15px -3px rgba(15,23,42,0.08),0 4px 6px -4px rgba(15,23,42,0.05)",
      "dark": "inset 0 0 0 1px rgba(255,255,255,0.07)"
    },
    "xl": {
      "light": "0 25px 50px -12px rgba(15,23,42,0.18)",
      "dark": "inset 0 0 0 1px rgba(255,255,255,0.08)"
    }
  },
  "motion": {
    "duration": {
      "instant": "80ms",
      "fast": "150ms",
      "normal": "240ms",
      "slow": "360ms",
      "deliberate": "600ms"
    },
    "easing": {
      "out": "cubic-bezier(0.16,1,0.3,1)",
      "in": "cubic-bezier(0.7,0,0.84,0)",
      "in_out": "cubic-bezier(0.83,0,0.17,1)",
      "spring": "cubic-bezier(0.34,1.56,0.64,1)"
    }
  },
  "density": {
    "comfortable": {
      "row_height": "56px",
      "padding": "16px",
      "font_body": "16px"
    },
    "compact": {
      "row_height": "44px",
      "padding": "12px",
      "font_body": "14px"
    },
    "dense": {
      "row_height": "32px",
      "padding": "8px",
      "font_body": "13px"
    }
  },
  "breakpoint": {
    "sm": "640px",
    "md": "768px",
    "lg": "1024px",
    "xl": "1280px",
    "2xl": "1536px"
  },
  "z_index": {
    "base": "0",
    "sticky": "100",
    "dropdown": "200",
    "modal": "300",
    "popover": "400",
    "toast": "500",
    "tooltip": "600"
  }
} as const;

export type Tokens = typeof tokens;

export type DriverStatus =
  | 'available'
  | 'en_route_to_pickup'
  | 'waiting_passenger'
  | 'on_trip'
  | 'on_break'
  | 'offline'
  | 'suspended';

export type RideStatus =
  | 'unassigned_urgent'
  | 'broadcasted'
  | 'in_assignment_window'
  | 'scheduled'
  | 'in_progress'
  | 'hold';

/** Returns a CSS var() reference. Example: cssVar('brand.primary') → 'var(--brand-primary)' */
export function cssVar(path: string): string {
  return `var(--${path.replace(/\./g, '-')})`;
}

export function getDriverStatusColor(
  status: DriverStatus,
  mode: 'light' | 'dark' = 'light',
): string {
  return tokens.color.driver_status[status][mode] as string;
}

export function getRideStatusBadge(
  status: RideStatus,
  mode: 'light' | 'dark' = 'light',
): { borderColor: string; bgColor: string } {
  const s = tokens.color.ride_status[status];
  return {
    borderColor: (s as any).border[mode] as string,
    bgColor: (s as any).bg[mode] as string,
  };
}
