// AUTOGENERATED — DO NOT EDIT (regenerate via: dart run build/flutter_build.dart)
// ignore_for_file: constant_identifier_names
import 'dart:ui';

/// Design tokens for remis_design_system.
/// Generated from tokens.json.
class RTokens {
  RTokens._();
  // TODO: generated by flutter_build.dart
}
